import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '@/Components/Footer'
import Navbar from '@/Components/Navbar'
import { SidebarProvider } from '@/Components/SidebarContext'
import Provider from '../Redux/Provider'
import SessionWrapper from "@/Components/SessionWrapper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden w-full relative`}
      >

        <SessionWrapper>
          <Provider>
            <SidebarProvider>
              <Navbar />
              {children}
              <Footer />
            </SidebarProvider>
          </Provider>
        </SessionWrapper>
      </body>
    </html>
  );
}
